# Generated by Django 5.1.2 on 2024-10-21 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_app', '0002_alter_document_subject_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification_code',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='verification_code',
            name='expires_by',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 21, 12, 2, 8, 1604, tzinfo=datetime.timezone.utc)),
        ),
    ]
